title: "Team Tres"
description: "Profiles, Projects, and Interests for the UH Community"
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: true
  repository_url: "https://github.com/Team-Tres"
gems:
  - jekyll-mentions
